services:
  - type: web
    name: fastapi-gemini-quiz-app
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
